import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Accessibility, Armchair, Bath, Check, Ear, Eye, Lightbulb, ShieldCheck, Soup, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import sammyFamily from "@/assets/sammy-family-cafe.jpg";

export const Route = createFileRoute("/preferences")({ head:()=>({meta:[{title:"Sammy’s accessibility preferences — FriendEase"},{name:"description",content:"Privately set accessibility and sensory priorities for your group."},{property:"og:title",content:"Accessibility preferences — FriendEase"},{property:"og:description",content:"Set private requirements as required, important, or nice to have."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: Preferences });
const prefs = [{n:"Step-free access",i:Accessibility},{n:"Accessible restroom",i:Bath},{n:"Accessible seating",i:Armchair},{n:"Low-noise environment",i:Volume2},{n:"Sensory-friendly lighting",i:Lightbulb},{n:"Wheelchair accessibility",i:Accessibility},{n:"Hearing accessibility",i:Ear},{n:"Visual accessibility",i:Eye},{n:"Dietary requirements",i:Soup}];
type Priority="Required"|"Important"|"Nice to have";
function Preferences(){ const [selected,setSelected]=useState<Record<string,Priority>>({"Low-noise environment":"Required","Sensory-friendly lighting":"Important","Accessible seating":"Required"});
return <div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr]">
  <aside><p className="text-sm font-bold text-primary">Angie, Doug & Sammy</p><h1 className="mt-2 text-4xl font-extrabold">What makes an outing work?</h1><p className="mt-4 leading-7 text-muted-foreground">Angie and Doug are planning with their 12-year-old son, Sammy, who is autistic. The family prefers predictable sound, visually engaging spaces, and corner or booth seating.</p><div className="mt-6 overflow-hidden rounded-lg"><img src={sammyFamily} width={1536} height={1024} alt="Sammy relaxing with Angie and Doug beside a cafe aquarium" className="aspect-[4/3] w-full object-cover"/></div></aside>
  <section><div className="rounded-lg border border-primary/20 bg-secondary p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-6 shrink-0 text-primary"/><div><h2 className="font-bold">Your accessibility preferences remain private.</h2><p className="mt-1 text-sm text-muted-foreground">FriendEase uses them only to find suitable places.</p></div></div></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2">{prefs.map(({n,i:Icon})=>{const value=selected[n];return <div key={n} className={`rounded-lg border p-4 transition ${value?"border-primary bg-secondary":"bg-background"}`}><button className="flex w-full items-center gap-3 text-left" onClick={()=>setSelected(s=>{const x={...s}; if(x[n]) delete x[n]; else x[n]="Nice to have"; return x})}><span className={`grid size-9 shrink-0 place-items-center rounded-md ${value?"bg-primary text-primary-foreground":"bg-muted"}`}><Icon className="size-5"/></span><span className="min-w-0 flex-1 font-semibold">{n}</span>{value&&<Check className="size-5 text-primary"/>}</button>{value&&<div className="mt-4 grid grid-cols-3 gap-1">{(["Required","Important","Nice to have"] as Priority[]).map(p=><button key={p} onClick={()=>setSelected(s=>({...s,[n]:p}))} className={`min-h-9 rounded-md px-1 text-[11px] font-bold ${value===p?"bg-primary text-primary-foreground":"bg-background text-muted-foreground"}`}>{p}</button>)}</div>}</div>})}</div>
  <div className="mt-7 flex justify-end"><Button asChild size="lg"><Link to="/plan">Continue to outing details</Link></Button></div></section>
</div><section className="mt-20 border-t pt-14"><p className="text-sm font-bold text-primary">A private journey, end to end</p><h2 className="mt-2 text-3xl font-bold">From preferences to a relaxed day out.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[{n:"01",t:"Plan privately",d:"Angie and Doug add the details that help Sammy feel at ease."},{n:"02",t:"Compare three strong matches",d:"FriendEase ranks venues without sending anyone’s needs to them."},{n:"03",t:"Enjoy the moment",d:"The family arrives knowing the space is likely to work for everybody."}].map((x,idx)=><article key={x.n} className="rounded-lg border bg-background p-6"><span className="text-sm font-extrabold text-primary">{x.n}</span><h3 className="mt-3 text-lg font-bold">{x.t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{x.d}</p>{idx===2&&<img src={sammyFamily} loading="lazy" width={1536} height={1024} alt="Sammy and his parents enjoying a calm cafe with an aquarium" className="mt-5 aspect-[16/9] w-full rounded-md object-cover"/>}</article>)}</div></section></div>}